### ISSUE TITLE
Problem compiling KataGo on Linux with CUDA 11

### ISSUE THREAD

**Issue by hdconradi** [lightvector/KataGo#244]
Hi,

I have recently purchased a NVIDIA graphics card for my linux (opensuse tumbleweed) powered pc in order to have KataGo run a bit faster ;-)
I have installed CUDA and CUDNN - both version 11, since 10 is not available (at least I have not been able to find it for my OS).

Since the precompiled executable requires CUDA version 10, I decided to build katago myself (which I did previously for OpenCL too).

I have use the v1.4.2-nets tag of katago (and tried v1.4.2 too).

cmake seems to be fine:
```
export CUDA_HOME=...
export CUDACXX=/usr/local/cuda/bin/nvcc
cmake . -DUSE_BACKEND=CUDA -DCUDNN_INCLUDE_DIR=$CUDA_HOME/include/

-- The C compiler identification is GNU 10.1.1
-- The CXX compiler identification is GNU 10.1.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
Building 'katago' executable for GTP engine and other tools
-DUSE_BACKEND=CUDA, using CUDA backend
-- The CUDA compiler identification is NVIDIA 11.0.167
-- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc
-- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc - works
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Detecting CUDA compile features
-- Detecting CUDA compile features - done
Including Git revision in the compiled executable, specify -DNO_GIT_REVISION=1 to disable
-- Found Git: /usr/bin/git (found version "2.27.0") 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /usr/local/cuda (found version "11.0") 
-- Found ZLIB: /usr/lib64/libz.so (found version "1.2.11") 
-- Found Boost: /usr/lib64/cmake/Boost-1.71.0/BoostConfig.cmake (found version "1.71.0") found components: system filesystem 
-- Configuring done
-- Generating done
-- Build files have been written to: $KATAGO/cpp
```

(I do however not understand that the C compiler identification is GNU 10.1.1, since I have gcc-9 first in the path, and that was necessary to make the cuda compiler happy which states: `gcc versions later than 9 are not supported!` - which however is a bit weird since the cuda rpm itself requires gcc-10.)

But then the actual build fails with:
```
$ make
[  1%] Generating program/gitinfoupdated.h
Scanning dependencies of target katago
[  2%] Building CXX object CMakeFiles/katago.dir/core/global.cpp.o

...[snipped]...

[ 42%] Building CXX object CMakeFiles/katago.dir/neuralnet/cudabackend.cpp.o
In file included from $KATAGO/cpp/neuralnet/cudabackend.cpp:2:
$KATAGO/cpp/neuralnet/cudabackend.cpp: In constructor ‘ConvLayer::ConvLayer(CudaHandles*, const ConvLayerDesc*, int, cudnnTensorStruct* const*, cudnnTensorStruct* const*, bool, bool)’:
$KATAGO/cpp/neuralnet/cudabackend.cpp:265:11: error: ‘CUDNN_CONVOLUTION_FWD_PREFER_FASTEST’ was not declared in this scope; did you mean ‘CUDNN_CONVOLUTION_BWD_FILTER_ALGO_3’?
  265 |           CUDNN_CONVOLUTION_FWD_PREFER_FASTEST,
      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
$KATAGO/cpp/neuralnet/../neuralnet/cudaerrorcheck.h:46:48: note: in definition of macro ‘CUDNN_ERR’
   46 | #define CUDNN_ERR(opName,x) { checkCudnnError((x),opName,__FILE__,#x,__LINE__); }
      |                                                ^
$KATAGO/cpp/neuralnet/cudabackend.cpp:259:32: error: ‘cudnnGetConvolutionForwardAlgorithm’ was not declared in this scope; did you mean ‘cudnnGetConvolutionForwardAlgorithm_v7’?
  259 |         CUDNN_ERR(name.c_str(),cudnnGetConvolutionForwardAlgorithm(
      |                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
$KATAGO/cpp/neuralnet/../neuralnet/cudaerrorcheck.h:46:48: note: in definition of macro ‘CUDNN_ERR’
   46 | #define CUDNN_ERR(opName,x) { checkCudnnError((x),opName,__FILE__,#x,__LINE__); }
      |                                                ^
make[2]: *** [CMakeFiles/katago.dir/build.make:480: CMakeFiles/katago.dir/neuralnet/cudabackend.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:96: CMakeFiles/katago.dir/all] Error 2
make: *** [Makefile:104: all] Error 2
```
What am I doing wrong, or what am I missing?
Or is this an issue with CUDA version 11?

Thanks in advance,
Heinz-Dieter

**Comment by lightvector** [comment]
Without looking into it in detail, I'm guessing based on your error messages that CUDA 11 introduced some backwards-incompatible changes to the API. Code that is written for CUDA 10 will not work on CUDA 11, and vice versa. So at some point I suppose KataGo will need to upgrade to CUDA 11, and also at that time, possibly anyone using still CUDA 10 will now be unable to run it, unless perhaps we specifically add some compile-time switches to compile different branches of code make both work.

**Comment by hdconradi** [comment]
Thank you,

unfortunately, this is exactly what I feared.
I will try again to install CUDA 10 - but I do not hold my breath ;-(

Probably I will have to wait for a new version of katago.
Thank you again for your great work!

**Comment by Harald-Han** [comment]
Replace cpp/neuralnet/cudabackend.cpp with the attached file. I have modified the code to make it compatible with cuDNN 8.0.0 but I could not try it on CUDA 11 since my system still runs CUDA 10. Good luck!

I'm running katago on Nvidia Jetson AGX Xavier. It was working fine on Jetpack 4.4 DP but fails to run on Jetpack 4.4. production release, which was announced a few days ago. What causes the trouble is the newly updated cuDNN libraries. But now it works OK again with the above modification.

[cudabackend.cpp.zip](https://github.com/lightvector/KataGo/files/4902963/cudabackend.cpp.zip)

**Comment by Harald-Han** [comment]
I also have katago installed on a Google Cloud Platform server running Ubuntu 18.04 + CUDA 11. Fortunately, however, cuDNN libraries were of version 7 so that I didn't have any problems in building and running katago. But just to check if my modifications mentioned above really work in CUDA 11, I upgraded cuDNN libraries from v7 to v8, which resulted in the same error you posted above in running 'make'. Then I replaced cudabackend.cpp with the one I edited and katago was built successfully, which has proved that the fixes work well on the CUDA 11 + cuDNN 8 environments.

**Comment by lightvector** [comment]
The changes you originally initiated here for CUDA 11 support are now part of the 1.7.0 release and at least so far things look good to me. Looks like everything is done here, thanks so much!
https://github.com/lightvector/KataGo/releases
