### ISSUE TITLE
Incompatible version of TensorRT

### ISSUE THREAD

**Issue by kennychenfs** [lightvector/KataGo#770]
I'm trying to run KataGo on Ubuntu 22.04. After installing cuda, cudnn and TensorRT, KataGo reports an incompatible version of TensorRT.

Here are the versions I tried.
KataGo: 1.12.4
cuda: 11.2, 11.7, 11.8
libcudnn: 8.5.0, 8.7.0
tensorrt: 8.5.1, 8.5.3
Do I need to install a different version of these?

**Comment by kennychenfs** [comment]
I solved it by compiling KataGo myself.
Compling guide is [here](https://github.com/lightvector/KataGo/blob/master/Compiling.md).
Also, properly installing cuda, cudnn, and tensorrt may help.(I didn't try) A guide is available on [discord](https://discord.com/channels/417022162348802048/583775968804732928/1082630477518745640).
